// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('alMakinah').config(function($stateProvider, $urlRouterProvider, $locationProvider) {
    'ngInject';
    $locationProvider.html5Mode(true);

    $stateProvider
      .state("dashboard", {
        abstract: true,
        templateUrl: "app/views/layouts/dashboard_layout.html",
        controller: "DashboardController"
      })
      .state("dashboard.home", {
        url: "/",
        templateUrl: "app/views/dashboard/index.html"
      })
      .state('sign_in', {
        url: '/sign_in',
        templateUrl: 'app/views/authentication/user_sign_in.html'
      })
      .state('sign_up', {
        url: '/sign_up',
        templateUrl: 'app/views/authentication/user_sign_up.html'
      })
      .state('gm_sign_in', {
        url: '/game_maker',
        templateUrl: 'app/views/authentication/gamemaker_sign_in.html'
      })
      .state('dashboard.topics', {
        url: '/topics',
        templateUrl: 'app/views/topics/topics.html'
      })
      .state('topic', {
        url: '/topics/:topicId',
        templateUrl: 'app/views/topics/topic.html'
      })
      .state('topic.quiz', {
        url: '/quizzes/:quizId',
        templateUrl: 'app/views/quizzes/quiz.html'
      })
      .state('topic.quiz.questions', {
        url: '/questions',
        templateUrl: 'app/views/questions/questions.html'
      })
      .state('topic.quiz.questions.new', {
        url: '/new',
        templateUrl: 'app/views/questions/new.html'
      });

    $urlRouterProvider.otherwise('/');
    $locationProvider.html5Mode(true);
  });

}).call(this);
