// Generated by CoffeeScript 1.10.0
(function() {
  angular.
    module('alMakinah', [
        'ngAnimate',
        'ngCookies',
        'ngSanitize',
        'ngStorage',
        'ui.router',
        'ui.bootstrap',
        'toaster',
        'ng-token-auth',
        'toastr'
    ]);

}).call(this);
