// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("quizical")
  .factory('AuthService', function ($rootScope, $auth, $log, $state, toastr) {

    return {
      getCurrentUser: function () {
        return $auth.validateUser()
      },
      registerUser: function (registrationForm) {
        $auth.submitRegistration(registrationForm)

        .then(function () {
          $state.go('sign_in');
          toastr.success('You have successfully registered.');
        }).catch(function (response) {
          $log.error(response);
        });
      },
      loginUser: function (loginForm) {
        $auth.submitLogin(loginForm)

        .then(function () {
          toastr.success('You have successfully logged in.');
          $state.go('user.topics');
        }).catch(function () {
          toastr.error('Wrong email or password.', 'ERROR!');
        });
      },
      logOutUser: function () {
        $auth.signOut()

        .then(function () {
          $state.go('sign_in');
          toastr.success('You have successfully logged out.');
        }).catch(function (response) {
          $log.error(response);
        })
      },
      authenticateUser: function () {
        $auth.validateUser()

        .then(function (resp) {
          // this.signedIn = true;
          // $rootScope.$broadcast('signedIn');
          // $log.log('authenticated');

          if (resp.configName !== 'default') {
            $state.go('403');
          }
        },
        function (resp) {
          if (resp.reason === 'unauthorized') {
            $state.go('401');
          }
        })
      },
      loginGameMaker: function (loginForm) {
        $auth.submitLogin(loginForm, {
          config: 'gameMaker'
        })

        .then(function () {
          $state.go('game_maker.topics');
          toastr.success('You have successfully logged in.');
        }).catch(function () {
          toastr.error('Wrong email or password.', 'ERROR!');
        })
      },
      logOutGameMaker: function () {
        $auth.signOut({
          config: 'gameMaker'
        })

        .then(function () {
          $state.go('game_maker.sign_in');
          toastr.success('You have successfully logged out.');
        }).catch(function (response) {
          $log.error(response);
        })
      },
      authenticateGameMaker: function () {
        $auth.validateUser()

        .then(function (resp) {
          if (resp.configName !== 'gameMaker') {
            $state.go('403');
          }
        },
        function () {
          $state.go('game_maker.sign_in')
        })
      }

    }

  });

}).call(this);
