// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("alMakinah").factory("Makinah", function() {
    var MakinahObj, app;
    app = {
      name: 'Al Makinah',
      version: '1.0.0',
      settings: {
        loginBg: false
      },
      hideFooterOn: ["dashboard.contacts", "dashboard.contacts.notes", "dashboard.calls"]
    };

    MakinahObj = {
      app: function() {
        return app;
      },
      loginBg: function() {
        return app.settings.loginBg;
      },
      get: function(attr) {
        return app.settings[attr];
      },
      set: function(attr, val) {
        return app.settings[attr] = val;
      }
    };

    return MakinahObj;
  });

}).call(this);
