// Generated by CoffeeScript 1.10.0
(function() {
  angular.module("alMakinah")
  .factory('TopicsService', function ($http, $auth,ENV_VARS) {
    var baseUrl = ENV_VARS.baseUrl + 'users/';

    return {
      getUserProfile: function (id) {
        return $http.get(baseUrl + id  + '.json');
      },
      updateUserProfile: function (data) {
        return $auth.updateAccount(data);
      },
      deleteUserAccount: function () {
        return $auth.destroyAccount();
      }
    };
  });
}).call(this);
